
# **The dataset includes information about:**

Customers who left within the last month – the column is called Churn. Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies. Customer account information – how long they had been a customer, contract, payment method, paperless billing, monthly charges, and total charges.Demographic info about customers – gender, age range, and if they have partners and dependents
---



In [1]:
#importing the important projects 
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")
display(df)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [3]:
#extracting the required parameters into another array
dff=df[["ed","employ","equip","callcard","wireless"]]
display(dff)
X = np.asanyarray(dff[["ed","employ","equip","callcard","wireless"]])
X[0:5]
y = np.asanyarray(df['churn'])
y [0:5]

ed  employ  equip  callcard  wireless
0    5.0     5.0    0.0       1.0       1.0
1    2.0     0.0    0.0       0.0       0.0
2    1.0     2.0    0.0       0.0       0.0
3    2.0    10.0    1.0       1.0       1.0
4    2.0    15.0    0.0       1.0       0.0
..   ...     ...    ...       ...       ...
195  1.0    23.0    0.0       1.0       0.0
196  1.0     7.0    0.0       1.0       0.0
197  1.0    10.0    0.0       1.0       0.0
198  4.0     5.0    0.0       1.0       1.0
199  2.0    22.0    1.0       1.0       1.0

[200 rows x 5 columns]

array([1., 1., 0., 0., 0.])

In [4]:
#preprocessing
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.6961288 , -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.6433592 , -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-1.42318853, -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [-0.6433592 , -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-0.6433592 ,  0.53441472, -0.85972695,  0.64686916, -0.63910148]])

In [5]:
from sklearn.model_selection import train_test_split
X_t, X_test, y_t, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_t.shape,  y_t.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_t,y_t)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [7]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1.])

In [8]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.56628588, 0.43371412],
       [0.56512867, 0.43487133],
       [0.5692309 , 0.4307691 ],
       [0.66540031, 0.33459969],
       [0.53373132, 0.46626868],
       [0.64105839, 0.35894161],
       [0.5218807 , 0.4781193 ],
       [0.58920219, 0.41079781],
       [0.45274683, 0.54725317],
       [0.56448138, 0.43551862],
       [0.48367103, 0.51632897],
       [0.5377661 , 0.4622339 ],
       [0.61409713, 0.38590287],
       [0.45624138, 0.54375862],
       [0.70304928, 0.29695072],
       [0.53491585, 0.46508415],
       [0.45624138, 0.54375862],
       [0.44860984, 0.55139016],
       [0.44229245, 0.55770755],
       [0.60276889, 0.39723111],
       [0.49305494, 0.50694506],
       [0.46039879, 0.53960121],
       [0.64369144, 0.35630856],
       [0.48080925, 0.51919075],
       [0.50260065, 0.49739935],
       [0.67474799, 0.32525201],
       [0.48015564, 0.51984436],
       [0.4885077 , 0.5114923 ],
       [0.54358463, 0.45641537],
       [0.66853111, 0.33146889],
       [0.

In [9]:
a=confusion_matrix(y_test, yhat)
print(a)

[[18  7]
 [ 9  6]]


In [10]:
acc=a[0,0]+a[1,1]
acc1=a[0,0]+a[1,0]+a[1,1]+a[0,1]

print(acc/acc1)

0.6
