In [1]:
import pandas as pd 
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing 
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")
display(df)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [3]:
df_=df[["cardten","ed","tenure","cardmon","employ","longmon"]]
display(df_)
X=np.asanyarray(df_[["cardten","ed","tenure","cardmon","employ","longmon"]])
X[0:6]
y=np.asanyarray(df['churn'])
y[0:6]

cardten   ed  tenure  cardmon  employ  longmon
0      125.0  5.0    11.0    15.25     5.0     4.40
1        0.0  2.0    33.0     0.00     0.0     9.45
2        0.0  1.0    23.0     0.00     2.0     6.30
3      880.0  2.0    38.0    23.25    10.0     6.05
4      145.0  2.0     7.0    23.75    15.0     7.10
..       ...  ...     ...      ...     ...      ...
195    720.0  1.0    55.0    14.25    23.0    17.35
196    435.0  1.0    34.0    12.75     7.0     6.00
197     80.0  1.0     6.0    12.50    10.0     3.85
198    780.0  4.0    24.0    32.75     5.0     8.70
199   1600.0  2.0    61.0    26.50    22.0    16.85

[200 rows x 6 columns]

array([1., 1., 0., 0., 0., 0.])

In [4]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:6]

array([[-0.55974431,  1.6961288 , -1.13518441,  0.06044721, -0.58477841,
        -0.74922681],
       [-0.69284848, -0.6433592 , -0.11604313, -0.97385292, -1.14437497,
        -0.23718629],
       [-0.69284848, -1.42318853, -0.57928917, -0.97385292, -0.92053635,
        -0.5565779 ],
       [ 0.24420489, -0.6433592 ,  0.11557989,  0.60303089, -0.02518185,
        -0.58192644],
       [-0.53844764, -0.6433592 , -1.32048283,  0.63694237,  0.53441472,
        -0.47546257],
       [ 0.90972576, -1.42318853,  1.505318  ,  0.51825219,  1.54168853,
         0.90349803]])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 6) (160,)
Test set: (40, 6) (40,)


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [7]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0.])

In [8]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.59253353, 0.40746647],
       [0.66193531, 0.33806469],
       [0.55738603, 0.44261397],
       [0.60453951, 0.39546049],
       [0.51575558, 0.48424442],
       [0.4949897 , 0.5050103 ],
       [0.46731913, 0.53268087],
       [0.62539789, 0.37460211],
       [0.43658381, 0.56341619],
       [0.68347471, 0.31652529],
       [0.60490191, 0.39509809],
       [0.68611601, 0.31388399],
       [0.46778237, 0.53221763],
       [0.45219944, 0.54780056],
       [0.60290827, 0.39709173],
       [0.61590601, 0.38409399],
       [0.49506909, 0.50493091],
       [0.61799851, 0.38200149],
       [0.49981598, 0.50018402],
       [0.5119706 , 0.4880294 ],
       [0.55992842, 0.44007158],
       [0.54795293, 0.45204707],
       [0.72197448, 0.27802552],
       [0.50701034, 0.49298966],
       [0.58895214, 0.41104786],
       [0.63250721, 0.36749279],
       [0.56743649, 0.43256351],
       [0.59332791, 0.40667209],
       [0.48155711, 0.51844289],
       [0.69794709, 0.30205291],
       [0.

In [9]:
a=confusion_matrix(y_test, yhat)
print(a)

[[23  2]
 [ 7  8]]


In [10]:
acc=a[0,0]+a[1,1]
acc1=a[0,0]+a[1,0]+a[1,1]+a[0,1]

print(acc/acc1)

0.775
